name: Upload bottles

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  upload-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_BINTRAY_USER: linuxbrewtestbot
      HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      UPSTREAM_PULL_REQUEST: 864
    steps:
      - name: Configure git
        uses: Homebrew/actions/git-ssh@master
        with:
          git_user: LinuxbrewTestBot
          git_email: testbot@linuxbrew.sh
          key: ${{secrets.SSH_KEY}}
      - name: Upload bottles
        run: |
          echo ${{github.event.review.user.login}} ${{github.event.review.state}} ${{github.event.review.body}}
          case ${{github.event.review.user.login}} in
            sjackman) echo Known reviewer ;;
            *) echo Unknown reviewer; exit 1 ;;
          esac
          case ${{github.event.review.body}} in https://github.com/brewsci/homebrew-bio/suites/*/artifacts/*)
            brew install unzip
            curl -L -o bottles.zip ${{github.event.review.body}}
            unzip bottles.zip
            brew update-reset
            brew test-bot --ci-upload --bintray-org=linuxbrew --root-url=https://linuxbrew.bintray.com/bottles-bio --git-name=LinuxbrewTestBot --git-email=testbot@linuxbrew.sh
          esac
